In [40]:
import pandas as pd
import re

In [41]:
#df = pd.read_csv('data/data_updated_discription.csv')
df = pd.read_csv('../data/data_added_description.csv', sep=";", quotechar='"', engine="python")

In [42]:
df.shape

(156, 104)

In [43]:
for i in df.columns:
    print(i)

id
name
type
category
email
recruitment_status
verified
recruitment_link
description
established
head
telegram_url
instagram_url
created_at
updated_at
head_user/sub
head_user/name
head_user/surname
head_user/picture
permissions/can_edit
permissions/can_delete
achievements/0/description
achievements/0/year
achievements/0/id
achievements/0/community_id
achievements/0/created_at
achievements/0/updated_at
achievements/1/description
achievements/1/year
achievements/1/id
achievements/1/community_id
achievements/1/created_at
achievements/1/updated_at
achievements/2/description
achievements/2/year
achievements/2/id
achievements/2/community_id
achievements/2/created_at
achievements/2/updated_at
achievements/3/description
achievements/3/year
achievements/3/id
achievements/3/community_id
achievements/3/created_at
achievements/3/updated_at
media/0/id
media/0/url
media/0/mime_type
media/0/entity_type
media/0/entity_id
media/0/media_format
media/0/media_order
media/1/id
media/1/url
media/1/mime_type
media/1/entity_type
media/1/entity_id
media/1/media_format
media/1/media_order
achievements/4/description
achievements/4/year
achievements/4/id
achievements/4/community_id
achievements/4/created_at
achievements/4/updated_at
achievements/5/description
achievements/5/year
achievements/5/id
achievements/5/community_id
achievements/5/created_at
achievements/5/updated_at
achievements/6/description
achievements/6/year
achievements/6/id
achievements/6/community_id
achievements/6/created_at
achievements/6/updated_at
achievements/7/description
achievements/7/year
achievements/7/id
achievements/7/community_id
achievements/7/created_at
achievements/7/updated_at
media/2/id
media/2/url
media/2/mime_type
media/2/entity_type
media/2/entity_id
media/2/media_format
media/2/media_order
media/3/id
media/3/url
media/3/mime_type
media/3/entity_type
media/3/entity_id
media/3/media_format
media/3/media_order
media/4/id
media/4/url
media/4/mime_type
media/4/entity_type
media/4/entity_id
media/4/media_format
media/4/media_order

In [44]:
df = df[df['type'] == 'club']
df

,id,name,type,category,email,recruitment_status,verified,recruitment_link,description,established,...,media/3/entity_id,media/3/media_format,media/3/media_order,media/4/id,media/4/url,media/4/mime_type,media/4/entity_type,media/4/entity_id,media/4/media_format,media/4/media_order
0,49,25th July Cinema,club,cultural,25july@nu.edu.kz,closed,True,https://docs.google.com/forms/d/e/1FAIpQLScf9r...,25th July Cinema Club is a collaborative hub f...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17,Accounting and Auditing Club,club,academic,aac@nu.edu.kz,closed,True,https://nu.edu.kz/clubs/aac/join,Accounting and Auditing Club (AAC) is a profes...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20,ACM@NU,club,academic,acmsc@nu.edu.kz,closed,True,https://forms.gle/h5cnGDpa9HQ5NLpR7,ACM@NU -is the Nazarbayev University branch of...,2017-02-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,150,Acoustic Night Community,club,cultural,acousticnight@nu.edu.kz,closed,True,NaN,Acoustic Night has been a part of Nazarbayev U...,2025-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63,Adventure Club,club,cultural,adventure.club@nu.edu.kz,closed,False,https://nu.edu.kz/clubs/adventure.club/join,Official Adventure Club at Nazarbayev Universi...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,110,Volunteers Club,club,social,volunteers@nu.edu.kz,closed,False,https://nu.edu.kz/clubs/volunteers/join,Our club brings all volunteers together to gai...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,4,Vox Club,club,academic,vox@nu.edu.kz,closed,True,https://www.google.com/,Our club avoided the COVID-19 crisis by commen...,2025-02-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,40,Women in Engineering (WEC),club,academic,wec@nu.edu.kz,closed,True,https://forms.gle/jSfuZxxrTkH9D2gVA,Women in Engineering (WEC) is a dynamic and su...,2020-01-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,103,YBS Kpop Cover Dance Club,club,sports,kpopcdc@nu.edu.kz,closed,False,https://nu.edu.kz/clubs/kpopcdc/join,Our club specializes on K-Pop cover dance and ...,2020-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,130,МБОУ СОШ Community,club,social,adilet.akhat@nu.edu.kz,closed,False,https://forms.gle/yCubFRNXdwx51uds9,A home for students who came from regular publ...,2025-08-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df = df[['id', 'name', 'category', 'email', 'description', 'established', 'telegram_url', 'instagram_url', ]]
df

,id,name,category,email,description,established,telegram_url,instagram_url
0,49,25th July Cinema,cultural,25july@nu.edu.kz,25th July Cinema Club is a collaborative hub f...,2020-09-01,https://t.me/CinemaJuly25th,https://www.instagram.com/xxv07/
1,17,Accounting and Auditing Club,academic,aac@nu.edu.kz,Accounting and Auditing Club (AAC) is a profes...,2020-09-01,https://t.me/nu__aac,https://www.instagram.com/nu__aac
2,20,ACM@NU,academic,acmsc@nu.edu.kz,ACM@NU -is the Nazarbayev University branch of...,2017-02-04,https://t.me/nuacmsc,https://www.instagram.com/nuacmsc/
3,150,Acoustic Night Community,cultural,acousticnight@nu.edu.kz,Acoustic Night has been a part of Nazarbayev U...,2025-10-19,NaN,https://www.instagram.com/acoustic.night/
4,63,Adventure Club,cultural,adventure.club@nu.edu.kz,Official Adventure Club at Nazarbayev Universi...,2020-09-01,https://t.me/adventure.club,https://www.instagram.com/adventure.club
...,...,...,...,...,...,...,...,...
151,110,Volunteers Club,social,volunteers@nu.edu.kz,Our club brings all volunteers together to gai...,2020-09-01,https://t.me/volunteers,https://www.instagram.com/volunteersclub/
152,4,Vox Club,academic,vox@nu.edu.kz,Our club avoided the COVID-19 crisis by commen...,2025-02-10,https://t.me,https://www.instagram.com/vox_phil_nu/
153,40,Women in Engineering (WEC),academic,wec@nu.edu.kz,Women in Engineering (WEC) is a dynamic and su...,2020-01-30,https://t.me/wec_ji,https://www.instagram.com/nu_wec/
154,103,YBS Kpop Cover Dance Club,sports,kpopcdc@nu.edu.kz,Our club specializes on K-Pop cover dance and ...,2020-09-01,https://t.me/kpopcdc,https://www.instagram.com/nu.ybs/
155,130,МБОУ СОШ Community,social,adilet.akhat@nu.edu.kz,A home for students who came from regular publ...,2025-08-14,NaN,NaN

In [46]:
to_remove = [
    'Body Ballet', 'Computer Graphics Club', 'Fitness and Nutrition',
    'higgsfield enjoyers', 'SG Ministry of Culture', 'Ministry of Sports and Health',
    'Ministry of External Affairs', 'NU Brainstorm', 'NU Cheerleading Club',
    'NU Graduate Student Union', 'NU Motorsports', 'Media Village',
    'NU Fashion Models Waacking Club', 'NU Rotaract', 'NU Stand Up Night',
    'NU Zumba', 'Pre-Med Club', 'SASA', 'SEDS Student Chapter',
    'SG Ministry of Research and Innovations', 'Smeshariki Enjoyers Club',
    'Student Rights Committee', 'МБОУ СОШ Community', 'Career and Advising Center'
]

df = df[~df['name'].isin(to_remove)]

#noticed a duplicate of clubs and removing it
df = df[df['id'] != 156]
df = df[df['id'] != 101]
df = df[df['id'] != 46]
df = df[df['id'] != 138]

In [47]:
df.isna().sum()

id                0
name              0
category          0
email             2
description       0
established       0
telegram_url     15
instagram_url     1
dtype: int64

In [48]:
df.loc[df['telegram_url'].isna(), 'name']

3                      Acoustic Night Community
25                                Business Club
40                        Game Development Club
59                                     LLL Club
63                    Model United Nations Club
67                                 Notion at NU
71     NU Association of International Students
77                                  NU Climbing
78                               NU Comedy Club
82                                   NU Decides
88                                 NU IMechE SC
100                                    NU Rover
102                                   NU SciPod
129                       SDSN Youth Kazakhstan
130                                     SEDS.KZ
Name: name, dtype: object

In [49]:
df.loc[df['instagram_url'].isna(), 'name']

129    SDSN Youth Kazakhstan
Name: name, dtype: object

### filling the telegram

In [50]:
df.loc[df['name'] == 'Acoustic Night Community', 'telegram_url'] = 'https://t.me/acousticnightcommunity'
df.loc[df['name'] == 'Business Club', 'telegram_url'] = 'https://t.me/nubusiness'
df.loc[df['name'] == 'Game Development Club', 'telegram_url'] = 'https://t.me/nu_gdc'
df.loc[df['name'] == 'LLL Club', 'telegram_url'] = 'https://t.me/nu_lll_club'
df.loc[df['name'] == 'Model United Nations Club', 'telegram_url'] = 'https://t.me/numunclub'
df.loc[df['name'] == 'Notion at NU', 'telegram_url'] = 'https://t.me/nu_notion'
df.loc[df['name'] == 'NU Association of International Students', 'telegram_url'] = 'https://t.me/aoisclub'
df.loc[df['name'] == 'NU Climbing', 'telegram_url'] = 'https://t.me/nuhikingcampingclimbing'
df.loc[df['name'] == 'NU Comedy Club', 'telegram_url'] = 'https://t.me/comedynu'
df.loc[df['name'] == 'NU Decides', 'telegram_url'] = 'NaN'
df.loc[df['name'] == 'NU IMechE SC', 'telegram_url'] = 'https://t.me/nuimeche'
df.loc[df['name'] == 'NU Psychology Club', 'telegram_url'] = 'https://t.me/nupsychology'
df.loc[df['name'] == 'NU Rover', 'telegram_url'] = 'https://t.me/nuroverkz'
df.loc[df['name'] == 'NU SciPod', 'telegram_url'] = 'https://t.me/NUSciPod'
df.loc[df['name'] == 'SDSN Youth Kazakhstan', 'telegram_url'] = 'https://t.me/sdsnyouth'
df.loc[df['name'] == 'SEDS.KZ', 'telegram_url'] = 'https://t.me/seds_kz'

## filling the instagramm

In [51]:
df.loc[df['name'] == 'NU Psychology Club', 'instagram_url'] = 'https://www.instagram.com/nupsychology/'
df.loc[df['name'] == 'SDSN Youth Kazakhstan', 'instagram_url'] = 'https://www.instagram.com/sdsnyouth.kazakhstan/'

## filling the email

In [52]:
df.loc[df['email'].isna(), 'name']

85                    NU GDC
129    SDSN Youth Kazakhstan
Name: name, dtype: object

In [53]:
df.loc[df['name'] == 'NU GDC', 'email'] = 'NaN'
df.loc[df['name'] == 'SDSN Youth Kazakhstan', 'email'] = 'sdsn@nu.edu.kz'

In [54]:
df.isna().sum()

id               0
name             0
category         0
email            0
description      0
established      0
telegram_url     0
instagram_url    0
dtype: int64

----

In [55]:
def clean_text(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"#{1,3}\s*", " ", text)
    text = re.sub(r"\*{1,2}(.+?)\*{1,2}", r"\1", text)
    text = re.sub(r"^\s*[-•]\s+", " ", text, flags=re.MULTILINE)
    text = re.sub(r"Location:.*?\n", " ", text)
    text = re.sub(r"\n+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [56]:
df['description'] = df['description'].apply(clean_text)

In [57]:
df.to_csv('../data/cleaned_data.csv')